version: "3"

services:
  pointguardnode0:
    container_name: pointguardnode0
    image: "pointguard/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-ethermint.log}
    volumes:
      - ./localnet-setup/node0/pointguard:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  pointguardnode1:
    container_name: pointguardnode1
    image: "pointguard/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-ethermint.log}
    volumes:
      - ./localnet-setup/node1/pointguard:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  pointguardnode2:
    container_name: pointguardnode2
    image: "pointguard/node"
    environment:
      - ID=2
      - LOG=${LOG:-ethermint.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/pointguard:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  pointguardnode3:
    container_name: pointguardnode3
    image: "pointguard/node"
    environment:
      - ID=3
      - LOG=${LOG:-ethermint.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/pointguard:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
